[package]
name = "rustimoji"
version = "2.0.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.23", features = ["derive"] }
clipboard = "0.5.0"
diacritics = "0.2.2"
glob = "0.3.1"
image = "0.25.6"
rofi = "0.4.0"
serde = { version = "1.0.216", features = ["derive"] }
