[package]
name = "rustimoji"
version = "1.0.1"
edition = "2021"

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.23", features = ["derive"] }
clipboard = "0.5.0"
glob = "0.3.1"
rofi = "0.4.0"
serde = { version = "1.0.216", features = ["derive"] }
